services:
  postgres:
    image: postgres:17
    container_name: postgres
    restart: unless-stopped
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d sofrosyne"]
      interval: 5s
      timeout: 5s
      retries: 20

  backend:
    image: sofrosyne:latest
    container_name: sofrosyne_backend
    build:
      context: .
      dockerfile: Dockerfile
      ## The command needs to be ./run_backend.R
      args:
        - GITHUB_PAT=${GITHUB_PAT}
    command: ./run_backend.R
    restart: unless-stopped
    env_file: .env
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy

  frontend:
    image: sofrosyne:latest
    container_name: sofrosyne_frontend
    build:
      context: .
      dockerfile: Dockerfile
      ## The command needs to be ./run_frontend.R
      args:
        - GITHUB_PAT=${GITHUB_PAT}
    command: ./run_frontend.R
    restart: unless-stopped
    env_file: .env
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  pgdata:
    name: sofrosyne_pgdata
